name: Tarea Automatizada de ejecuci贸n de pruebas

env:
  DOTNET_VERSION: '8.x'                     # la versi贸n de .NET

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Configurando la versi贸n de NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
          # dotnet-quality: 'ga'
      - name: Restaurar los paquetes
        run: dotnet restore 
      - name: Ejecutar pruebas
        run: dotnet test --collect:"XPlat Code Coverage"

      - name: ReportGenerator
        uses: danielpalme/ReportGenerator-GitHub-Action@5.3.7
        with:
          reports: ./*/*/*/coverage.cobertura.xml
          targetdir: Cobertura
          reporttypes: MarkdownSummary;MarkdownAssembliesSummary;MarkdownSummaryGithub;MarkdownDeltaSummary
      # - uses: actions/checkout@v4
      # - name: Configurando .NET Core
      #   uses: actions/setup-dotnet@v4
      #   with:
      #     dotnet-version: ${{ env.DOTNET_VERSION }}
      # - name: Restaurar los paquetes
      #   run: dotnet restore 
      # - name: Publicar la aplicaci贸n de manera local
      #   run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/publish
      # - name: Subir el artefacto para el job de despliegue
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: .net-app
      #     path: ${{env.DOTNET_ROOT}}/publish

